### ISSUE TITLE
USER STORY: Game Photos

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#11]
As a **user**, I want to be able to **view photos of the escape room game themes and rooms on the booking website**, so that I can **get a sneak peek of the games and get excited about the experience.**

## **Acceptance Criteria:**
- Acceptance Criteria 1: Have photos of the games in visible places for the user to see.
- Acceptance Criteria 2: Have photos for the blog/sales page.
- Acceptance Criteria 3: Have links to the companies social media page where users can find more images. 

## **Tasks:**
- [x] Task 1: Create the hero section photo slideshow that shows users playing the room. 
- [x] Task 2: Create Cloudinary photo functionality in the Blog model so admin user can create blogs with photos about the rooms.
- [x] Task 3: Create links to socials in the footer and the account page.
