### ISSUE TITLE
USER STORY: User Account Deletion

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#13]
As a **user** I want to be able to **delete my own account and request all my data be removed from your servers/databases** so that I can **exercise my data protection rights**.

## **Acceptance Criteria:**
- Acceptance Criteria 1: Have a button or form within the user account that allows the user to delete their account and all booking data.
- Acceptance Criteria 2: The user shouldn't be able to delete without being prompted with a warning.

## **Tasks:**
- [x] Task 1: Create a button that allows the user to delete their account and all booking data.
- [x] Task 2: Create a modal that pops up to inform the user, allowing them to either confirm or cancel
- [x] Task 3: Redirect to the home page once done successfully.
