### ISSUE TITLE
USER STORY: User Update Account Information

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#14]
As a **user** I want to be able to **edit my account details** so that I can **keep the booking process smooth and easy even if my email or other data changes**.

## **Acceptance Criteria:**
- Acceptance Criteria 1: Once logged in, the user should be able to see their information and edit any fields.
- Acceptance Criteria 2: User should see results immediately on their account page. 

## **Tasks:**
- [x] Task 1: Create an account page that pulls the users data from the allauth model
- [x] Task 2: Display the data to the user and create a button navigation to an edit page
- [x] Task 3: Create edit page that displays the current data but allows users to delete and update the information
- [x] Task 4: Redirect back to the account page to view the updated information
