### ISSUE TITLE
USER STORY: Room Description and Information

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#2]
As a **user**, I want to be able to **view all available escape room games on the booking website, including their descriptions, and any other information** so that **I can make an informed decision on which game to reserve.**

## **Acceptance Criteria:**
- Acceptance Criteria 1: Have a page that displays all the available games.
- Acceptance Criteria 2: Have a more detailed view of each of the games.
- Acceptance Criteria 3: Direct the user to the booking page when viewing the rooms. 

## **Tasks:**
- [x] Task 1: Create a page that create cards for each of the rooms that are available. 
- [x] Task 2: Have a simple view for each rooms, and create a link to a more detailed view. 
- [x] Task 3: Detailed view needs to give a deeper synopsis of the room and crate a link to the booking page. 
- [x] Task 4: Have images available for the rooms that help visually tell their story.
