### ISSUE TITLE
USER STORY: Promotion and Sale Advert Admin Management

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#21]
As an **admin user**, I want to be able to **manage special promotions, discounts, or packages for escape room games, including creating, updating, or expiring promotions** so that I can **attract more customers and boost sales.**

## **Acceptance Criteria:**
- Acceptance Criteria 1: Admin users should be able to create blog posts with images
- Acceptance Criteria 2: Admin users should be able to delete old posts and edit old posts

## **Tasks:**
- [x] Task 1: Create blog app, and the model with all appropriate model fields. 
- [x] Task 2: Configure admin view to allow Admin users to filter and see all old posts. 
- [x] Task 3: Set blog model with Cloudinary functionality.
