### ISSUE TITLE
USER STORY: Room Addition 

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#22]
As an **admin user** I want to be able to **add new games to the website as the company builds and expands** so that we can **have the newest and most up to date information about our games immediately visible to our customer**

## **Acceptance Criteria:**
- Acceptance Criteria 1: Admin users should be able to add rooms, with details, and photos to the admin site. 

## **Tasks:**
- [x] Task 1: Update Reservation models and app to have Room model. 
- [x] Task 2: Room model should have Cloudinary function  for images, 
- [x] Task 3: Admin users should have access to available rooms and be able to add or delete them from database.
