### ISSUE TITLE
USER STORY: Game Timeslot Add/Remove Function

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#23]
As an **admin user** I want to be able to **add or remove time slots available for booking** so that we can **adjust our business hours to match the flow of the business traffic to our location.**

## **Acceptance Criteria:**
- Acceptance Criteria 1: On the admin site, an admin user should be able to add time slots or remove them. 
- Acceptance Criteria 2: There should be no duplicate time slots. 

## **Tasks:**
- [x] Task 1: Update the Reservation model to have a Game Time model.
- [x] Task 2: Create defensive code that doesn't allow for duplicated slots. 
- [x] Task 3: Create a time slot for every hour of the day, only allowing users to choose the predetermined slots.
