### ISSUE TITLE
USER STORY: Booking Reservation

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#24]
As a **user** I want to be able to **create a reservation using my account information, and having all the applicable data visible such as group sizes, date, time, etc** so that I can **quick and easily secure a booking**.

## **Acceptance Criteria:**
- Acceptance Criteria 1: When a customer navigates to the booking request form, data from their account populates appropriate fields.
- Acceptance Criteria 2: Booking process shows the cost for the number of participants, comment, and user information
- Acceptance Criteria 3: Allow users to sign-in to the site before making the booking

## **Tasks:**
- [x] Create a booking form using the Reservation model
- [x] Validate if user is signed in and if so display the reservation availability page
- [x] Pull user information from user account and populate name, email, and phone to the form
