### ISSUE TITLE
USER STORY: User Controlled Booking Modification 

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#5]
As a **user**, I want to be able to **easily cancel or reschedule my escape room game reservations through the booking website,** so that **I can adjust my plans quickly if needed**.

## **Acceptance Criteria:**
- Acceptance Criteria 1: Allow a user to delete a booking for a room in the future, but not same-day
- Acceptance Criteria 2: Allow a user to change either the time, room, or date of the event, or all three. 
- Acceptance Criteria 3: Show the information for the new booking immediately on their account

## **Tasks:**
- [x] Task 1: Create the edit functionality, showing only the available slots to the user
- [x] Task 2: Display the old and new data so the user can confirm the data before proceeding
- [x] Task 3: Create a modal pop-up for when a user choses to delete a booking, warning the user and allowing them to either confirm or suspend the deletion
- [x] Task 4: The user account should update immediately with the new information, either new booking data or the game being removed from the account view.
