### ISSUE TITLE
USER STORY: Promotion Adverts

### ISSUE THREAD

**Issue by cmjimerson1s** [cmjimerson1s/PP4_enigma_machine#7]
As a **user**, I want to be able to **view special promotions, discounts, or packages for escape room games on the booking website**, so that I can **take advantage of any available deals and save on my bookings.**

## **Acceptance Criteria:**
- Acceptance Criteria 1: Have a page where users can view current sales an promotions. 
- Acceptance Criteria 2: The page should display all the previous sales as well to give the user an understanding of trends.

## **Tasks:**
- [x] Task 1: Create a 'blog' app that allows the admin to create and post sales to the user facing website.
- [x] Task 2: Create a page that displays the previous posts to the user.
- [x] Task 3: Allow the user to click on the blog post to get a more detailed view of the blog content.
- [x] Task 4: Detailed view should show user related content.
